#include "leetcode/problems/magical-string.h"

namespace leetcode {
namespace problem_481 {

// Build the magical string incrementally.
// s = "1221121221221121122..." is generated by reading its own group sizes.
// The string dictates: group[i] says how many consecutive equal chars the i-th
// group has. We always start the next group with the opposite char.
static int solution1(int n) {
  if (n <= 0) return 0;
  if (n <= 3) return 1;  // "1" -> 1, "12" -> 1, "122" -> 1

  std::vector<int> s;
  s.reserve(n + 1);
  s.push_back(1);
  s.push_back(2);
  s.push_back(2);

  int head = 2;  // index in s giving the current group size
  int val = 1;   // the value of the next group
  while (static_cast<int>(s.size()) < n) {
    int cnt = s[head++];
    for (int i = 0; i < cnt && static_cast<int>(s.size()) < n; ++i) {
      s.push_back(val);
    }
    val = val == 1 ? 2 : 1;
  }

  int ones = 0;
  for (int i = 0; i < n; ++i) {
    if (s[i] == 1) ++ones;
  }
  return ones;
}

MagicalStringSolution::MagicalStringSolution() {
  setMetaInfo({
      .id = 481,
      .title = "Magical String",
      .url = "https://leetcode.com/problems/magical-string"
  });
  registerStrategy({.name = "Incremental Construction",
                    .expected = "Accepted",
                    .time_complexity = "O(n)",
                    .space_complexity = "O(n)",
                    .tags = {"Simulation", "String"}},
                   solution1);
}

int MagicalStringSolution::magicalString(int n) {
  return getSolution()(n);
}

}  // namespace problem_481
}  // namespace leetcode
